name = "leagueweb-lite"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
SITE_NAME = "酒馆战棋联赛"
WEB_VERSION = "0.1.0"
SESSION_SECRET = "change-me-in-production"

[[d1_databases]]
binding = "DB"
database_name = "leagueweb-lite"
database_id = "6ea23928-ba15-419c-b07d-4b29ee71e63c"
